

export const light= {
    colors: {
      navbarBackground: '#f8f9fa',  
      logoText: '#000000',  
      navLinksBackground: '#ffffff', 
      navItemText: '#212529',  
      navItemHover: '#007bff',  
      navItemActive: '#0056b3', 
      navButtonText: '#212529',  
      buttonBackground: '#007bff',  
      buttonHover: '#007bff', 
      mobileMenuButton: '#007bff',  
      mobileMenuBackground: '#f8f9fa', 
      mobileNavItemText: '#212529', 
      cartIcon: '#007bff',  
      cartCountBackground: '#ff0000',  
      cartCountText: '#ffffff',  
      selectBackground: '#ffffff',  
      selectText: '#000000', 
      navItemHoverBackground: '#e2e6ea',  
      selectBorder: '#007bff',  
      selectHover: '#0056b3',  
      cartIconColor: '#007bff',  
      cartIconHover: '#0056b3',  
      TopNavbarBackground: '#eff2f4',  
      navbarContainerBackground: '#f8f9fa',  
      navLinkText: '#333',
      cardBackground: '#ffffff',
      cardPropertyBackground: '#ffffff',
      cardBodyText: '#000000',
      colorText: '#000000',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#000000',
      countdownBackground : '#ffffff',
      featureBackground : '#f8f9fa',
      cardText: '#000000',
      border :'#dee2e6',
      cardBodyBackground: '#ffffff',
      differentCardBorder:'#f8f9fa',
      linkHoverText: '#0056b3',
      differentCardBackground: '#ffffff',
      contentBackground: '#f8f9fa',
      differentCardText: '#000000',
      titleText: '#FFD700',
      descriptionText: '#000000',
      iconBackground: '#f8f9fa',
      imageWrapperBackground: '#f8f9fa',
      imageBackground : '#f8f9fa',
      linkText: '#007bff',
      containerBackground : '#f8f9fa',
      principalDetailsBackground: '#ffffff',
      textColor: '#000000',
      hoverCardBackground: '#f8f9fa',
      infoTextColor : '#000000',
      cartItemBorder : '#dee2e6',
      cartItemImageBorder : '#dee2e6',
      cartItemTitle : '#000000',
      cartItemPrice : '#000000',
      incrDecButtonBackground : '#007bff',
      incrDecButtonHoverText : '#000000',
      cartItemButtonBackground : '#dee2e6',
      cartItemButtonHover : '#007bff',
      cartItemQuantityText : '#000000',
      colorCircleBorder : '#dee2e6',
      sizeCircleBackground : '#dee2e6',
      sizeCircleText : '#000000',
      sizeCircleBorder : '#dee2e6',
      sidebarBackground: '#f8f9fa',
      sidebarText: '#000000',
      linkHoverBackground: '#f8f9fa',
      cardHeaderBackground  : '#ffffff',
      tableWrapperBackground: '#ffffff',
      tableHeaderBackground: '#f8f9fa',
      tableHeaderText: '#000000',
      buttonHoverBackground: '#007bff',
      emptyMessageBackground : '#ffffff',
      wrapperBackground : '#f8f9fa',
      cardHeaderText: '#000000',
      subtitleText : '#ffcc00',
      goldAccent: '#d4af37',
      boxShadow  : '0 4px 12px rgba(0, 0, 0, 0.1)',
      objectBackground: '#ffffff',
      featureTextColor: '#000000',
      selectedBorder: '#007bff',
      noSelectedBorder : "#ccc",
      hoverBorder   : '#007bff',
      noHoverBorder : '#dee2e6',
      selectedBackground  : '#f8f9fa',  
      noSelectedBackground : '#ffffff',
      selectedText: '#000000',
      noSelectedText : '#000000',
      iconHoverColor: '#0056b3',
      hoverContainerBackground: '#e2e6ea',
      imageBorder: '#dee2e6',
      hoverBackground: '#f8f9fa',
      hoverText: '#007bff',
      incrDecBackground: '#ffffff',
      primary: '#007bff',
      incrDecButtonHover: '#0056b3',
      cartItemButtonText: '#ffffff',
      emptyMessageText: '#6c757d',
      emptyMessageBorder: '#dee2e6',
      loadingText: '#212529',
      loadingBackground: '#f8f9fa',
      emptyMessageBackgroundStart: '#ffffff',
      emptyMessageBackgroundEnd: '#f8f9fa',
      carrierContainerBackground: '#f8f9fa',
      highlight: '#ffc107',
      paymentContainerBackground: '#f8f9fa',
      activeLinkText: '#007bff',
      activeLinkBackground: '#e2e6ea',
      tableWrapperBackgroundStart: '#ffffff',
      tableWrapperBackgroundEnd: '#f8f9fa',
      tableBackground: '#ffffff',
      tableText: '#000000',
      tableRowHoverBackground: '#e2e6ea',
      buttonBorder: '#007bff',
      buttonBackgroundStart: '#007bff',
      buttonBackgroundEnd: '#0056b3',
      buttonText: '#ffffff',
      wrapperBackgroundStart: '#ffffff',
      wrapperBackgroundEnd: '#f8f9fa',
      cardBorder: '#dee2e6',
      successBackground: '#28a745',
      successHover: '#218838',
      dangerBackground: '#dc3545',
      dangerHover: '#c82333',
      textSecondaryColor: '#6c757d',
      defaultCircleBackground  : '#dee2e6',
      textMuted: '#6c757d',
      overlayText: '#ffffff',
      inputBackground: '#ffffff',
      inputBorder : '#dee2e6',
      inputText: '#495057',
    }    
  };