export const themes = {
  light: {
    colors: {
      navbarBackground: '#f8f9fa',  
      logoText: '#000000',  
      navLinksBackground: '#ffffff', 
      navItemText: '#212529',  
      navItemHover: '#007bff',  
      navItemActive: '#0056b3', 
      navButtonText: '#007bff',  
      buttonBackground: '#e9ecef',  
      buttonHover: '#007bff', 
      mobileMenuButton: '#007bff',  
      mobileMenuBackground: '#f8f9fa', 
      mobileNavItemText: '#212529', 
      cartIcon: '#007bff',  
      cartCountBackground: '#ff0000',  
      cartCountText: '#ffffff',  
      selectBackground: '#ffffff',  
      selectText: '#000000', 
      navItemHoverBackground: '#e2e6ea',  
      selectBorder: '#007bff',  
      selectHover: '#0056b3',  
      cartIconColor: '#007bff',  
      cartIconHover: '#0056b3',  
      TopNavbarBackground: '#eff2f4',  
      navbarContainerBackground: '#f8f9fa',  
      navLinkText: '#333',
      cardBackground: '#ffffff',
      cardPropertyBackground: '#ffffff',
      cardBodyText: '#000000',
      colorText: '#000000',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#000000',
      countdownBackground : '#ffffff',
    },
  },
  dark: {
    colors: {
      navbarBackground: '#121212',  
      logoText: '#ffffff',  
      navLinksBackground: '#1e1e1e', 
      navItemText: '#e0e0e0',  
      navItemHover: '#bb86fc',  
      navItemActive: '#3700b3', 
      navButtonText: '#bb86fc', 
      buttonBackground: '#333333', 
      buttonHover: '#bb86fc',  
      mobileMenuButton: '#ffffff',  
      mobileMenuBackground: '#1e1e1e', 
      mobileNavItemText: '#e0e0e0', 
      cartIcon: '#ffffff',  
      cartCountBackground: '#ff0000',  
      cartCountText: '#ffffff',  
      selectBackground: '#333333', 
      selectText: '#ffffff', 
      navItemHoverBackground: '#444444', 
      selectBorder: '#bb86fc', 
      selectHover: '#3700b3',  
      cartIconColor: '#ffffff',  
      cartIconHover: '#bb86fc',  
      TopNavbarBackground: '#282828',  
      navbarContainerBackground: '#121212', 
      navLinkText: '#ffffff',
      cardBackground: '#333333',
      cardPropertyBackground: '#333333',
      cardBodyText: '#ffffff',
      colorText: '#ffffff',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#ffffff',
      countdownBackground : '#333333',
    },
  },
  custom: {
    colors: {
      navbarBackground: '#ff3366',
      logoText: '#fff',
      navLinksBackground: '#ff3366',
      navItemText: '#fff',
      navItemHover: '#ff6699',
      navItemActive: '#ff6699',
      navButtonText: '#ff3366',
      buttonBackground: '#fff',
      buttonHover: '#ff6699',
      mobileMenuButton: '#fff',
      mobileMenuBackground: '#ff3366',
      mobileNavItemText: '#fff',
      cartIcon: '#fff',
      cartCountBackground: '#ff6699',
      cartCountText: '#fff',
      selectBackground: '#ff3366',
      selectText: '#fff',
      navItemHoverBackground: '#ff6699',
      selectBorder: '#fff',
      selectHover: '#ff6699',
      cartIconColor: '#fff',
      cartIconHover: '#ff6699',
      TopNavbarBackground: '#ff3366',
      navbarContainerBackground: '#ff3366',
      navLinkText: '#fff',
      cardBackground: '#ff3366',
      cardPropertyBackground: '#ff3366',
      cardBodyText: '#fff',
      colorText: '#fff',
      discountBadgeBackground: '#ff6699',
      discountBadgeText: '#fff',
      countdownText : '#fff',
      countdownBackground : '#ff3366',
    },
  },
  theme1: {
    colors: {
      navbarBackground: '#ffcc00',
      logoText: '#333',
      navLinksBackground: '#ffeb99',
      navItemText: '#333',
      navItemHover: '#ff9900',
      navItemActive: '#ff6600',
      navButtonText: '#333',
      buttonBackground: '#ffe680',
      buttonHover: '#ffcc00',
      mobileMenuButton: '#333',
      mobileMenuBackground: '#ffeb99',
      mobileNavItemText: '#333',
      cartIcon: '#333',
      cartCountBackground: '#ff0000',
      cartCountText: '#fff',
      selectBackground: '#ffeb99',
      selectText: '#333',
      navItemHoverBackground: '#ffd27f',
      selectBorder: '#ffcc00',
      selectHover: '#ff9900',
      cartIconColor: '#333',
      cartIconHover: '#ff9900',
      TopNavbarBackground: '#ffcc00',
      navbarContainerBackground: '#ffeb99',
      navLinkText: '#333',
      cardBackground: '#ffeb99',
      cardPropertyBackground: '#ffeb99',
      cardBodyText: '#333',
      colorText: '#333',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#fff',
      countdownText : '#333',
      countdownBackground : '#ffeb99',
    },
  },
  theme2: {
    colors: {
      navbarBackground: '#4caf50',
      logoText: '#ffffff',
      navLinksBackground: '#a5d6a7',
      navItemText: '#ffffff',
      navItemHover: '#388e3c',
      navItemActive: '#1b5e20',
      navButtonText: '#ffffff',
      buttonBackground: '#81c784',
      buttonHover: '#4caf50',
      mobileMenuButton: '#ffffff',
      mobileMenuBackground: '#a5d6a7',
      mobileNavItemText: '#ffffff',
      cartIcon: '#ffffff',
      cartCountBackground: '#ff0000',
      cartCountText: '#ffffff',
      selectBackground: '#a5d6a7',
      selectText: '#ffffff',
      navItemHoverBackground: '#66bb6a',
      selectBorder: '#4caf50',
      selectHover: '#388e3c',
      cartIconColor: '#ffffff',
      cartIconHover: '#388e3c',
      TopNavbarBackground: '#4caf50',
      navbarContainerBackground: '#a5d6a7',
      navLinkText: '#ffffff',
      cardBackground: '#a5d6a7',
      cardPropertyBackground: '#a5d6a7',
      cardBodyText: '#ffffff',
      colorText: '#ffffff',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#ffffff',
      countdownBackground : '#a5d6a7',
    },
  },
  theme3: {
    colors: {
      navbarBackground: '#303f9f',
      logoText: '#ffffff',
      navLinksBackground: '#c5cae9',
      navItemText: '#ffffff',
      navItemHover: '#283593',
      navItemActive: '#1a237e',
      navButtonText: '#ffffff',
      buttonBackground: '#9fa8da',
      buttonHover: '#303f9f',
      mobileMenuButton: '#ffffff',
      mobileMenuBackground: '#c5cae9',
      mobileNavItemText: '#ffffff',
      cartIcon: '#ffffff',
      cartCountBackground: '#ff0000',
      cartCountText: '#ffffff',
      selectBackground: '#c5cae9',
      selectText: '#ffffff',
      navItemHoverBackground: '#7986cb',
      selectBorder: '#303f9f',
      selectHover: '#283593',
      cartIconColor: '#ffffff',
      cartIconHover: '#283593',
      TopNavbarBackground: '#303f9f',
      navbarContainerBackground: '#c5cae9',
      navLinkText: '#ffffff',
      cardBackground: '#c5cae9',
      cardPropertyBackground: '#c5cae9',
      cardBodyText: '#ffffff',
      colorText: '#ffffff',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#ffffff', 
      countdownBackground : '#c5cae9',
    },
  },
};
