export const themes = {
  light: {
    colors: {
      navbarBackground: '#ffffff',
      logoText: '#333',
      navLinksBackground: '#f3f3f3',
      navItemText: '#333',
      navItemHover: '#ff6600',
      navItemActive: '#ff6600',
      navButtonText: '#333',
      buttonBackground: '#f3f3f3',
      buttonHover: '#ff6600',
      mobileMenuButton: '#333',
      mobileMenuBackground: '#ffffff',
      mobileNavItemText: '#333',
      cartIcon: '#333',
      cartCountBackground: '#ff0000',
      cartCountText: '#fff',
      selectBackground: '#f3f3f3',
      selectText: '#333',
    },
  },
  dark: {
    colors: {
      navbarBackground: '#1a1a1a',
      logoText: '#fff',
      navLinksBackground: '#333',
      navItemText: '#fff',
      navItemHover: '#ff6600',
      navItemActive: '#ff6600',
      navButtonText: '#fff',
      buttonBackground: '#333',
      buttonHover: '#ff6600',
      mobileMenuButton: '#fff',
      mobileMenuBackground: '#333',
      mobileNavItemText: '#fff',
      cartIcon: '#fff',
      cartCountBackground: '#ff0000',
      cartCountText: '#fff',
      selectBackground: '#333',
      selectText: '#fff',
    },
  },
  custom: {
    colors: {
      navbarBackground: '#ff3366',
      logoText: '#fff',
      navLinksBackground: '#ff3366',
      navItemText: '#fff',
      navItemHover: '#ff6699',
      navItemActive: '#ff6699',
      navButtonText: '#ff3366',
      buttonBackground: '#fff',
      buttonHover: '#ff6699',
      mobileMenuButton: '#fff',
      mobileMenuBackground: '#ff3366',
      mobileNavItemText: '#fff',
      cartIcon: '#fff',
      cartCountBackground: '#ff6699',
      cartCountText: '#fff',
      selectBackground: '#ff3366',
      selectText: '#fff',
    },
  },
};
