export const themes = {
  light: {
    colors: {
      navbarBackground: '#f8f9fa',  
      logoText: '#000000',  
      navLinksBackground: '#ffffff', 
      navItemText: '#212529',  
      navItemHover: '#007bff',  
      navItemActive: '#0056b3', 
      navButtonText: '#007bff',  
      buttonBackground: '#e9ecef',  
      buttonHover: '#007bff', 
      mobileMenuButton: '#007bff',  
      mobileMenuBackground: '#f8f9fa', 
      mobileNavItemText: '#212529', 
      cartIcon: '#007bff',  
      cartCountBackground: '#ff0000',  
      cartCountText: '#ffffff',  
      selectBackground: '#ffffff',  
      selectText: '#000000', 
      navItemHoverBackground: '#e2e6ea',  
      selectBorder: '#007bff',  
      selectHover: '#0056b3',  
      cartIconColor: '#007bff',  
      cartIconHover: '#0056b3',  
      TopNavbarBackground: '#eff2f4',  
      navbarContainerBackground: '#f8f9fa',  
      navLinkText: '#333',
      cardBackground: '#ffffff',
      cardPropertyBackground: '#ffffff',
      cardBodyText: '#000000',
      colorText: '#000000',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#000000',
      countdownBackground : '#ffffff',
      featureBackground : '#f8f9fa',
      cardText: '#000000',
      border :'#dee2e6',
      cardBodyBackground: '#ffffff',
      differentCardBorder:'#f8f9fa',
      linkHoverText: '#0056b3',
      differentCardBackground: '#ffffff',
      contentBackground: '#f8f9fa',
      differentCardText: '#000000',
      imageBackground: '#ffffff',
      titleText: '#FFD700',
      descriptionText: '#000000',
      iconBackground: '#f8f9fa',
      imageWrapperBackground: '#f8f9fa',
      imageBackground : '#f8f9fa',
      linkText: '#007bff',
      containerBackground : '#f8f9fa',
      principalDetailsBackground: '#ffffff',
      textColor: '#000000',
      hoverCardBackground: '#f8f9fa',
      infoTextColor : '#000000',
      cartItemBorder : '#dee2e6',
      cartItemImageBorder : '#dee2e6',
      cartItemTitle : '#000000',
      cartItemPrice : '#000000',
      incrDecButtonBackground : '#007bff',
      incrDecButtonHoverText : '#000000',
      cartItemButtonBackground : '#dee2e6',
      cartItemButtonHover : '#007bff',
      cartItemQuantityText : '#000000',
      colorCircleBorder : '#dee2e6',
      sizeCircleBackground : '#dee2e6',
      sizeCircleText : '#000000',
      sizeCircleBorder : '#dee2e6',

      
    },
  },
  dark: {
    colors: {
      navbarBackground: '#121212',  
      logoText: '#ffffff',  
      navLinksBackground: '#1e1e1e', 
      navItemText: '#e0e0e0',  
      navItemHover: '#bb86fc',  
      navItemActive: '#3700b3', 
      navButtonText: '#bb86fc', 
      buttonBackground: '#333333', 
      buttonHover: '#bb86fc',  
      mobileMenuButton: '#ffffff',  
      mobileMenuBackground: '#1e1e1e', 
      mobileNavItemText: '#e0e0e0', 
      cartIcon: '#ffffff',  
      cartCountBackground: '#ff0000',  
      cartCountText: '#ffffff',  
      selectBackground: '#333333', 
      selectText: '#ffffff', 
      navItemHoverBackground: '#444444', 
      selectBorder: '#bb86fc', 
      selectHover: '#3700b3',  
      cartIconColor: '#ffffff',  
      cartIconHover: '#bb86fc',  
      TopNavbarBackground: '#282828',  
      navbarContainerBackground: '#121212', 
      navLinkText: '#ffffff',
      cardBackground: '#333333',
      cardPropertyBackground: '#333333',
      cardBodyText: '#ffffff',
      colorText: '#ffffff',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#ffffff',
      countdownBackground : '#333333',
      featureBackground : '#1e1e1e',
      cardText: '#ffffff',
      border :'#333333',
      cardBodyBackground: '#333333',
      differentCardBorder:'#1e1e1e',
      linkHoverText: '#bb86fc',
      differentCardBackground: '#1e1e1e',
      contentBackground: '#1e1e1e',
      differentCardText: '#ffffff',
      imageBackground: '#1e1e1e',
      titleText: '#FFD700',
      descriptionText: '#ffffff',
      iconBackground: '#1e1e1e',
      imageWrapperBackground: '#1e1e1e',
      imageBackground : '#1e1e1e',
      linkText: '#bb86fc',
      containerBackground : '#1e1e1e',
      principalDetailsBackground: '#333333',
      textColor: '#ffffff',
      hoverCardBackground: '#1e1e1e',
      infoTextColor : '#ffffff',
      cartItemBorder : '#333333',
      cartItemImageBorder : '#333333',
      cartItemTitle : '#ffffff',
      cartItemPrice : '#ffffff',
      incrDecButtonBackground : '#333333',
      incrDecButtonHoverText : '#ffffff',
      cartItemButtonBackground : '#333333',
      cartItemButtonHover : '#bb86fc',
      cartItemQuantityText : '#ffffff',
      colorCircleBorder : '#333333',
      sizeCircleBackground : '#333333',
      sizeCircleText : '#ffffff',
      sizeCircleBorder : '#333333',
    },
  },
  custom: {
    colors: {
      navbarBackground: '#ff3366',
      logoText: '#fff',
      navLinksBackground: '#ff3366',
      navItemText: '#fff',
      navItemHover: '#ff6699',
      navItemActive: '#ff6699',
      navButtonText: '#ff3366',
      buttonBackground: '#fff',
      buttonHover: '#ff6699',
      mobileMenuButton: '#fff',
      mobileMenuBackground: '#ff3366',
      mobileNavItemText: '#fff',
      cartIcon: '#fff',
      cartCountBackground: '#ff6699',
      cartCountText: '#fff',
      selectBackground: '#ff3366',
      selectText: '#fff',
      navItemHoverBackground: '#ff6699',
      selectBorder: '#fff',
      selectHover: '#ff6699',
      cartIconColor: '#fff',
      cartIconHover: '#ff6699',
      TopNavbarBackground: '#ff3366',
      navbarContainerBackground: '#ff3366',
      navLinkText: '#fff',
      cardBackground: '#ff3366',
      cardPropertyBackground: '#ff3366',
      cardBodyText: '#fff',
      colorText: '#fff',
      discountBadgeBackground: '#ff6699',
      discountBadgeText: '#fff',
      countdownText : '#fff',
      countdownBackground : '#ff3366',
      cardText: '#fff',
      border :'#ff3366',
      cardBodyBackground: '#ff3366',
      differentCardBorder:'#ff3366',
      linkHoverText: '#ff6699',
      differentCardBackground: '#ff3366',
      contentBackground: '#ff3366',
      differentCardText: '#fff',
      imageBackground: '#ff3366',
      titleText: '#FFD700',
      descriptionText: '#fff',
      iconBackground: '#ff3366',
      imageWrapperBackground: '#ff3366',
      imageBackground : '#ff3366',
      linkText: '#ff3366',
      containerBackground : '#ff3366',
      principalDetailsBackground: '#ff3366',
      textColor: '#fff',
      hoverCardBackground: '#ff3366',
      infoTextColor : '#fff',
      cartItemBorder : '#ff3366',
      cartItemImageBorder : '#ff3366',
      cartItemTitle : '#fff',
      cartItemPrice : '#fff',
      incrDecButtonBackground : '#ff3366',
      incrDecButtonHoverText : '#fff',
      cartItemButtonBackground : '#ff3366',
      cartItemButtonHover : '#ff6699',
      cartItemQuantityText : '#fff',
      colorCircleBorder : '#ff3366',
      sizeCircleBackground : '#ff3366',
      sizeCircleText : '#fff',
      sizeCircleBorder : '#ff3366',
    },
  },
  theme1: {
    colors: {
      navbarBackground: '#ffcc00',
      logoText: '#333',
      navLinksBackground: '#ffeb99',
      navItemText: '#333',
      navItemHover: '#ff9900',
      navItemActive: '#ff6600',
      navButtonText: '#333',
      buttonBackground: '#ffe680',
      buttonHover: '#ffcc00',
      mobileMenuButton: '#333',
      mobileMenuBackground: '#ffeb99',
      mobileNavItemText: '#333',
      cartIcon: '#333',
      cartCountBackground: '#ff0000',
      cartCountText: '#fff',
      selectBackground: '#ffeb99',
      selectText: '#333',
      navItemHoverBackground: '#ffd27f',
      selectBorder: '#ffcc00',
      selectHover: '#ff9900',
      cartIconColor: '#333',
      cartIconHover: '#ff9900',
      TopNavbarBackground: '#ffcc00',
      navbarContainerBackground: '#ffeb99',
      navLinkText: '#333',
      cardBackground: '#ffeb99',
      cardPropertyBackground: '#ffeb99',
      cardBodyText: '#333',
      colorText: '#333',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#fff',
      countdownText : '#333',
      countdownBackground : '#ffeb99',
      featureBackground : '#ffeb99',
      cardText: '#333',
      border :'#ffeb99',
      cardBodyBackground: '#ffeb99',
      differentCardBorder:'#ffeb99',
      linkHoverText: '#ff9900',
      differentCardBackground: '#ffeb99',
      contentBackground: '#ffeb99',
      differentCardText: '#333',
      imageBackground: '#ffeb99',
      titleText: '#FFD700',
      descriptionText: '#333',
      iconBackground: '#ffeb99',
      imageWrapperBackground: '#ffeb99',
      imageBackground : '#ffeb99',
      linkText: '#ffcc00',
      containerBackground : '#ffeb99',
      principalDetailsBackground: '#ffeb99',
      textColor: '#333',
      hoverCardBackground: '#ffeb99',
      infoTextColor : '#333',
      cartItemBorder : '#ffeb99',
      cartItemImageBorder : '#ffeb99',
      cartItemTitle : '#333',
      cartItemPrice : '#333',
      incrDecButtonBackground : '#ffeb99',
      incrDecButtonHoverText : '#333',
      cartItemButtonBackground : '#ffeb99',
      cartItemButtonHover : '#ff9900',
      cartItemQuantityText : '#333',
      colorCircleBorder : '#ffeb99',
      sizeCircleBackground : '#ffeb99',
      sizeCircleText : '#333',
      sizeCircleBorder : '#ffeb99',
    },
  },
  theme2: {
    colors: {
      navbarBackground: '#4caf50',
      logoText: '#ffffff',
      navLinksBackground: '#a5d6a7',
      navItemText: '#ffffff',
      navItemHover: '#388e3c',
      navItemActive: '#1b5e20',
      navButtonText: '#ffffff',
      buttonBackground: '#81c784',
      buttonHover: '#4caf50',
      mobileMenuButton: '#ffffff',
      mobileMenuBackground: '#a5d6a7',
      mobileNavItemText: '#ffffff',
      cartIcon: '#ffffff',
      cartCountBackground: '#ff0000',
      cartCountText: '#ffffff',
      selectBackground: '#a5d6a7',
      selectText: '#ffffff',
      navItemHoverBackground: '#66bb6a',
      selectBorder: '#4caf50',
      selectHover: '#388e3c',
      cartIconColor: '#ffffff',
      cartIconHover: '#388e3c',
      TopNavbarBackground: '#4caf50',
      navbarContainerBackground: '#a5d6a7',
      navLinkText: '#ffffff',
      cardBackground: '#a5d6a7',
      cardPropertyBackground: '#a5d6a7',
      cardBodyText: '#ffffff',
      colorText: '#ffffff',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#ffffff',
      countdownBackground : '#a5d6a7',
      featureBackground : '#a5d6a7',
      cardText: '#ffffff',
      border :'#a5d6a7',
      cardBodyBackground: '#a5d6a7',
      differentCardBorder:'#a5d6a7',
      linkHoverText: '#388e3c',
      differentCardBackground: '#a5d6a7',
      contentBackground: '#a5d6a7',
      differentCardText: '#ffffff',
      imageBackground: '#a5d6a7',
      titleText: '#FFD700',
      descriptionText: '#ffffff',
      iconBackground: '#a5d6a7',
      imageWrapperBackground: '#a5d6a7',
      imageBackground : '#a5d6a7',
      linkText: '#4caf50',
      containerBackground : '#a5d6a7',
      principalDetailsBackground: '#a5d6a7',
      textColor: '#ffffff',
      hoverCardBackground: '#a5d6a7',
      infoTextColor : '#ffffff',
      cartItemBorder : '#a5d6a7',
      cartItemImageBorder : '#a5d6a7',
      cartItemTitle : '#ffffff',
      cartItemPrice : '#ffffff',
      incrDecButtonBackground : '#a5d6a7',
      incrDecButtonHoverText : '#ffffff',
      cartItemButtonBackground : '#a5d6a7',
      cartItemButtonHover : '#388e3c',
      cartItemQuantityText : '#ffffff',
      colorCircleBorder : '#a5d6a7',
      sizeCircleBackground : '#a5d6a7',
      sizeCircleText : '#ffffff',
      sizeCircleBorder : '#a5d6a7',
    },
  },
  theme3: {
    colors: {
      navbarBackground: '#303f9f',
      logoText: '#ffffff',
      navLinksBackground: '#c5cae9',
      navItemText: '#ffffff',
      navItemHover: '#283593',
      navItemActive: '#1a237e',
      navButtonText: '#ffffff',
      buttonBackground: '#9fa8da',
      buttonHover: '#303f9f',
      mobileMenuButton: '#ffffff',
      mobileMenuBackground: '#c5cae9',
      mobileNavItemText: '#ffffff',
      cartIcon: '#ffffff',
      cartCountBackground: '#ff0000',
      cartCountText: '#ffffff',
      selectBackground: '#c5cae9',
      selectText: '#ffffff',
      navItemHoverBackground: '#7986cb',
      selectBorder: '#303f9f',
      selectHover: '#283593',
      cartIconColor: '#ffffff',
      cartIconHover: '#283593',
      TopNavbarBackground: '#303f9f',
      navbarContainerBackground: '#c5cae9',
      navLinkText: '#ffffff',
      cardBackground: '#c5cae9',
      cardPropertyBackground: '#c5cae9',
      cardBodyText: '#ffffff',
      colorText: '#ffffff',
      discountBadgeBackground: '#ff0000',
      discountBadgeText: '#ffffff',
      countdownText : '#ffffff', 
      countdownBackground : '#c5cae9',
      featureBackground : '#c5cae9',
      cardText: '#ffffff',
      border :'#c5cae9',
      cardBodyBackground: '#c5cae9',
      differentCardBorder:'#c5cae9',
      linkHoverText: '#283593',
      differentCardBackground: '#c5cae9',
      contentBackground: '#c5cae9',
      differentCardText: '#ffffff',
      imageBackground: '#c5cae9',
      titleText: '#FFD700',
      descriptionText: '#ffffff',
      iconBackground: '#c5cae9',
      imageWrapperBackground: '#c5cae9',
      imageBackground : '#c5cae9',
      linkText: '#303f9f',
      containerBackground : '#c5cae9',
      principalDetailsBackground: '#c5cae9',
      textColor: '#ffffff',
      hoverCardBackground: '#c5cae9',
      infoTextColor : '#ffffff',
      cartItemBorder : '#c5cae9',
      cartItemImageBorder : '#c5cae9',
      cartItemTitle : '#ffffff',
      cartItemPrice : '#ffffff',
      incrDecButtonBackground : '#c5cae9',
      incrDecButtonHoverText : '#ffffff',
      cartItemButtonBackground : '#c5cae9',
      cartItemButtonHover : '#283593',
      cartItemQuantityText : '#ffffff',
      colorCircleBorder : '#c5cae9',
      sizeCircleBackground : '#c5cae9',
      sizeCircleText : '#ffffff',
      sizeCircleBorder : '#c5cae9',
    },
  },
};
